# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'M3U8KitDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for M3U8KitDemo

  target 'M3U8KitDemoTests' do
   pod "TS2MP4"
  end

end
