# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Media' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  	pod 'SSKeychain', '~> 1.2.2'
	pod 'VENTouchLock', '~> 1.0'
    pod 'TS2MP4'
  # Pods for Media

end
